// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package driver_backend

const (
	Version     = "v0.0.1"
	GitCommit   = "49cd839"          // the commit JUST BEFORE the release
	VersionDate = "2024-08-14 14:45" // UTC
)
