- display_name: Adobe Sensei - Summer [Jun-Aug 2021]
  filepath: configs/workload_templates/trace_summer.json
  num_sessions: 1105
  num_training_events: 193127
  large: true
  key: adobe_sensei_summer
- display_name: 3 Concurrent Sessions - 8 Trainings Each
  filepath: configs/workload_templates/3-session-8-training-all-simultaneous.json
  num_sessions: 3
  num_training_events: 24
  large: false
  key: 3concurrent8training
- display_name: 5 Concurrent Sessions - 8 Trainings Each
  filepath: configs/workload_templates/5-session-8-training-all-simultaneous.json
  num_sessions: 5
  num_training_events: 40
  large: false
  key: 5concurrent8training
- display_name: Batch FCFS Basic Test
  filepath: configs/workload_templates/fcfs_test.json
  num_sessions: 2
  num_training_events: 2
  large: false
  key: batch_fcfs_test