#- display_name: Adobe Sensei - Summer 2021 (June, July, & August) v1
#  filepath: configs/workload_templates/trace_summer_2021.json
#  num_sessions: 3647
#  num_training_events: 163152
#  large: true
#  key: adobe_sensei_summer
- display_name: Adobe Sensei - Summer 2021 (June, July, & August) # v2
  filepath: configs/workload_templates/trace_summer_2021_v2.json
  num_sessions: 3502
  num_training_events: 140005
  large: true
  key: adobe_sensei_summer_v2
- display_name: Adobe Sensei - 1st Wk June 2021
  filepath: configs/workload_templates/trace_june_1st_week_2021.json
  num_sessions: 214
  num_training_events: 828
  large: true
  key: adobe_sensei_june_1st_wk_2021
- display_name: Adobe Sensei - June 2021 Weeks 1 & 2
  filepath: configs/workload_templates/trace_june_weeks_1_and_2_2021.json
  num_sessions: 453
  num_training_events: 1949
  large: true
  key: adobe_sensei_june_2021_wks_1_and_2
- display_name: Adobe Sensei - 1st Wk July 2021 # v2
  filepath: configs/workload_templates/trace_july_1st_week_2021.json
  num_sessions: 71
  num_training_events: 106
  large: true
  key: adobe_sensei_july_1st_wk_2021
- display_name: Adobe Sensei - June 2021
  filepath: configs/workload_templates/trace_june_2021.json
  num_sessions: 860
  num_training_events: 7827
  large: true
  key: adobe_sensei_june_2021
- display_name: Adobe Sensei - July 2021 # v2
  filepath: configs/workload_templates/trace_july_2021_v2_60sec.json
  num_sessions: 525
  num_training_events: 6371
  large: true
  key: adobe_sensei_july_v2_60sec_2021
- display_name: Adobe Sensei - June 1st - 3rd, 2021 # v2
  filepath: configs/workload_templates/trace_june1st_thru_3rd.json
  num_sessions: 130
  num_training_events: 237
  large: true
  key: adobe_sensei_june_1st_thru_3rd
- display_name: Adobe Sensei - August 2021
  filepath: configs/workload_templates/trace_august_2021.json
  num_sessions: 1606
  num_training_events: 28880
  large: true
  key: adobe_sensei_august_2021
- display_name: 3 Concurrent Sessions - 8 Trainings Each
  filepath: configs/workload_templates/3-session-8-training-all-simultaneous.json
  num_sessions: 3
  num_training_events: 24
  large: false
  key: 3concurrent8training
- display_name: 5 Concurrent Sessions - 8 Trainings Each
  filepath: configs/workload_templates/5-session-8-training-all-simultaneous.json
  num_sessions: 5
  num_training_events: 40
  large: false
  key: 5concurrent8training
- display_name: Batch FCFS Basic Test
  filepath: configs/workload_templates/fcfs_test.json
  num_sessions: 2
  num_training_events: 2
  large: false
  key: batch_fcfs_test
- display_name: 4 Sessions Varied Training
  filepath: configs/workload_templates/four-sessions-varied-training.json
  num_sessions: 4
  num_training_events: 16
  large: false
  key: 4_sessions_varied_training
- display_name: Single Session, 3 Trainings 
  filepath: configs/workload_templates/single_session_3_trainings.json
  num_sessions: 1
  num_training_events: 3
  large: false
  key: single_session_3_trainings
- display_name: 8 Sessions [39.53sec Avg. IAT, 22.95sec Avg. Duration]
  filepath: configs/workload_templates/Template-8Session-39.53IAT-22.95Dur.json
  num_sessions: 1
  num_training_events: 3
  large: false
  key: template_8session_39.53iat_22.95duration